2D and 3D dam break in laminar and turbulence model

diff --git a/turbulence_2D/Allclean b/turbulence_2D/Allclean
--- a/turbulence_2D/Allclean
+++ b/turbulence_2D/Allclean
@@ -1,20 +1,31 @@
 #!/bin/sh
 cd ${0%/*} || exit 1    # Run from this directory
 
-# Source tutorial clean functions
-. $WM_PROJECT_DIR/bin/tools/CleanFunctions
+# Check if the script is being run from an OpenFOAM case directory
+if [ ! -d "system" ] || [ ! -d "constant" ]; then
+    echo "Error: This script should be run from an OpenFOAM case directory."
+    exit 1
+fi
 
-keepCases="damBreak"
-loseCases="damBreakFine"
+# Remove all time directories (numeric folders like 0.1, 1, 10, 100)
+echo "Removing time directories..."
+find . -maxdepth 1 -type d -regex './[0-9]+.[0-9]*' -exec rm -rf {} +
+find . -maxdepth 1 -type d -regex './[0-9]*' -exec rm -rf {} +
 
-for case in $keepCases
-do
-    (cd $case && foamCleanTutorials)
-done
+# Remove post-processing results
+if [ -d "postProcessing" ]; then
+    echo "Removing postProcessing directory..."
+    rm -rf postProcessing
+fi
 
-for case in $loseCases
-do
-    removeCase $case
-done
+# Remove processor directories (from parallel runs)
+echo "Removing processor directories..."
+rm -rf processor*
+
+# Remove log files and other generated files
+echo "Removing log files and other generated files..."
+rm -f *.foam log.* *.OpenFOAM *.Identifier
+
+echo "Clean-up complete!"
 
 #------------------------------------------------------------------------------
